### ISSUE TITLE
Build instructions for Ubuntu 16.04

### ISSUE THREAD

**Issue by PBug90** [dmakarov/p4ls#18]
I am not able to compile with the scripts used in the CICD pipelines and also not with the homebrew setup mentioned in the README.

I also tried using gcc-9 with g++-9,  but that didnt work either.

Output from the compile step:

`-- [hunter] ZLIB_ROOT: /home/p4/.hunter/_Base/c2296fd/278e076/5022c31/Install (ver.: 1.2.11-p1)
CMake Error at /home/p4/.hunter/_Base/c2296fd/278e076/5022c31/Install/lib/cmake/ZLIB/ZLIBConfig.cmake:36 (add_library):
  add_library cannot create ALIAS target "ZLIB::ZLIB" because target
  "ZLIB::zlib" is IMPORTED.
`

**Comment by dmakarov** [comment]
It looks like the Hunter snapshot isn't able to build the boost library on Ubuntu 16.04. Can you install the latest boost, rapidjson, and cmake (at least version 3.11) on your system?  I'll make RapidJson package not to be required, so that the path to the RapidJson headers could be set directly. Then the following command should generate the build files without Hunter

```
cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DHUNTER_ENABLED=OFF -DUNITTESTS_ENABLED=OFF -DRAPIDJSON_INCLUDE_DIRS=/home/p4/local/include ..
```

**Comment by PBug90** [comment]
I have installed latest cmake (3.19.1), boost (1.75) and rapidjson. Rapidjson resides in p4ls/build folder and is found by cmake with the following command:

`
p4@ubuntu-16:~/p4ls/build$ cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DHUNTER_ENABLED=OFF -DUNITTESTS_ENABLED=OFF -DRapidJSON_DIR=/home/p4/p4ls/build/rapidjson/ .
`

Nevertheless, building the project still does not succeed:

```
p4@ubuntu-16:~/p4ls/build$ cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DHUNTER_ENABLED=OFF -DUNITTESTS_ENABLED=OFF -DRAPIDJSON_INCLUDE_DIRS=/home/p4/p4ls/rapidjson/include/rapidjson/ .
-- RapidJSON found. Headers: /home/p4/p4ls/rapidjson/include
-- Configuring done
-- Generating done
-- Build files have been written to: /home/p4/p4ls/build
p4@ubuntu-16:~/p4ls/build$ cmake --build .
[6/10] Building CXX object server/lsp/CMakeFiles/lsp.dir/lsp_server.cpp.o
FAILED: /usr/bin/g++  -I../server/p4l -isystem ../rapidjson/include/rapidjson -O3 -DNDEBUG -g -Wall -Werror -Wextra -fvisibility=hidden -fvisibility-inlines-hidden -std=gnu++17 -MD -MT server/lsp/CMakeFiles/lsp.dir/lsp_server.cpp.o -MF server/lsp/CMakeFiles/lsp.dir/lsp_server.cpp.o.d -o server/lsp/CMakeFiles/lsp.dir/lsp_server.cpp.o -c ../server/lsp/lsp_server.cpp
../server/lsp/lsp_server.cpp:5:10: fatal error: rapidjson/istreamwrapper.h: No such file or directory
    5 | #include <rapidjson/istreamwrapper.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by dmakarov** [comment]
It’s strange that cmake generated `-isystem ../rapidjson/include/rapidjson` command line option. Not that it should matter, but maybe it would be better to place rapidjson in some other location, outside p4ls/.

Just fyi I removed p4c frontend from the project a while ago, so p4ls currently is not doing semantic analysis of p4 source code and not very useful at the moment.

**Comment by PBug90** [comment]
I also tried to put the rapidjson source in my home directory but I still could not get it to work. Anyway, since the P4 semantic analysis is missing I am going to close this issue.
