### ISSUE TITLE
lsp-common.el has been removed from lsp

### ISSUE THREAD

**Issue by tarsius** [dmakarov/p4ls#2]
https://github.com/emacs-lsp/lsp-mode/commit/439df1e463b3778cea5ddcdb2fccbf27b6a9fb5f

**Comment by dmakarov** [comment]
I updated the package to not require lsp-common. However, further update is needed to match the new lsp-mode interface.

Do you use p4ls or simply monitor the failures of melpa packages?

**Comment by tarsius** [comment]
> Do you use p4ls or simply monitor the failures of melpa packages?

The latter. (I work more on the Emacsmirror than Melpa, but that too.)

**Comment by dmakarov** [comment]
Fixed in aba46babff3acc4c92b3c7b77a1d803bf367de64
